version: "3.8"

services:
  olt-backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olt-backup
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - backup-data:/app/backups
      - /var/log/olt-backup:/var/log
    environment:
      - TZ=${TZ:-America/Bahia}
    network_mode: host   # necess√°rio para acessar as OLTs na rede local

volumes:
  backup-data:
    driver: local
